# Generated by Django 5.0.1 on 2024-02-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbowl_squares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Square',
        ),
    ]
