# Generated by Django 5.0.1 on 2024-02-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbowl_squares', '0002_takensquare_delete_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='takensquare',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
